In [6]:
!conda install numpy

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [8]:
import numpy as np

In [12]:
arr = np.array([1,2,3,'as'])

In [14]:
arr

array(['1', '2', '3', 'as'], dtype='<U11')

In [16]:
arr = np.array([1,2,3,4])

In [18]:
print(arr)

[1 2 3 4]


In [24]:
arr.shape

(4,)

In [26]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [28]:
arr2.shape

(2, 3)

In [66]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr2[0:,1:]

array([[2, 3],
       [5, 6]])

In [78]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])